In [ ]:
#Qsn#:https://www.hackerrank.com/challenges/np-arrays/problem
import numpy as np

def arrays(arr):
  
  #res =np.sort(arr)
  #return res.astype(np.float)
  return np.array(arr[::-1], float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)


1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [ ]:
#QSN#- https://www.hackerrank.com/challenges/np-shape-reshape/problem
import numpy as np

arr = input().strip().split(' ')
arr = np.array(arr,int)
print(np.reshape(arr,(3,3)))


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#QSN#- https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem
rows, cols = map(int, input("Please enter no of rows & columns").split())

array1 = np.array([input().strip().split() for _ in range(rows)], int)
Tarr = array1.transpose()
Farr= array1.flatten()

print("Tranpose of array: \n", Tarr)
print("Flateen of array: ", Farr)


Please enter no of rows & columns2 2
2 3 
4 5
Tranpose of array: 
 [[2 4]
 [3 5]]
Flateen of array:  [2 3 4 5]


In [ ]:
#QSN# https://www.hackerrank.com/challenges/np-concatenate/problem


#The first line contains space separated integers Cols in each array, Rows of 1st array and Rows of second row.
#The next  lines contains the space separated elements of the  columns.
#After that, the next  lines contains the space separated elements of the  columns.

Cols, Row1, Row2 = map(int,input("Please enter no of columns in each array, Rows of array1, Rows of array2: ").split(' '))
Array1 = np.array([input().split() for _ in range(Cols)],int)
Array2 = np.array([input().split() for _ in range(Row1)],int)

print(np.concatenate((Array1, Array2), axis = 0))

Please enter no of columns in each array, Rows of array1, Rows of array2 4 3 2
1 2
1 2
1 2
1 2
3 4 
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
#QSN# - https://www.hackerrank.com/challenges/np-zeros-and-ones/problem
N = tuple(map(int, input().split()))
print(np.zeros(N, int))
print(np.ones(N, int))

2 2 3
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [ ]:
#QSN#6 -https://www.hackerrank.com/challenges/np-eye-and-identity/problem
print(np.eye(*map(int, input().split())))

7 6
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#QSN# - https://www.hackerrank.com/challenges/np-array-mathematics/problem

N, M = map(int, input().split())

array1 = np.array([list(map(int, input("Please enter integers of Array1").split())) for n in range(N)])
array2 = np.array([list(map(int, input("Please enter integers of Array2").split())) for n in range(N)])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 // array2)
print(array1 % array2)
print(array1 ** array2)

1 4
Please enter integers of Array11 2 3 4 
Please enter integers of Array25 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [ ]:
#QSN# - https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem
array = np.array(input().split(),float)

print(np.floor(array))
print(np.ceil(array))
print(np.rint(array))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [ ]:
#QSN# - https://www.hackerrank.com/challenges/np-min-and-max/problem

N, M = map(int, input().split())
storage = np.array([input().split() for _ in range(N)],int)
print(np.max(np.min(storage, axis=1), axis=0))




4 2
2 5
3 7
1 3
4 0
3


In [ ]:
#QSN - https://www.hackerrank.com/challenges/np-mean-var-and-std/problem



2 5
3 7
1 3
4 0

In [109]:
#QSN - https://www.hackerrank1.com/challenges/np-mean-var-and-std/problem

N,M = map(int,input().split())
A = np.array([input().split() for _ in range(N)], int)
print(A.mean(axis=1))
print(A.var(axis=0))
print(A.std())

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


In [ ]:
#QSN# - https://www.hackerrank.com/challenges/np-dot-and-cross/problem



2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


In [110]:
#QQSN - https://www.hackerrank.com/challenges/np-dot-and-cross/problem

n = int(input())
a = np.array([input().split() for _ in range(n)], int)
b = np.array([input().split() for _ in range(n)], int)
print(np.dot(a, b))


2
1  2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [111]:
#QSN - https://www.hackerrank.com/challenges/np-inner-and-outer/problem
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A, B), np.outer(A, B), sep='\n')

0 1
2 3
3
[[0 0]
 [2 3]]


In [114]:
#QSN- https://www.hackerrank.com/challenges/np-polynomials/problem

poly = [float(x) for x in input().split()]
x = float(input())

print(np.polyval(poly, x))

1.1 2 3
0
3.0


In [115]:
#QSN - https://www.hackerrank.com/challenges/np-sum-and-prod/problem

N, M = map(int, input().split())
A = np.array([input().split() for _ in range(N)], int)
print(np.prod(np.sum(A, axis=0), axis=0))

2 2
1 2
3 4
24
